Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.network "forwarded_port", guest: 3000, host: 3000
    config.ssh.forward_agent = true 
    config.ssh.forward_x11 = true
    config.vm.provider "virtualbox" do |v|
	  v.memory = 4096
	  v.cpus = 4
	end
    config.vm.synced_folder "experiments/", "/home/vagrant/experiments"
end
